# apiVersion: v1
# kind: Pod
# metadata: 
#   name: env
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     env:
#     - name: course
#       valueFrom:
#         configMapKeyRef:
#           name: course-config
#           key: course
#     - name: duration
#       valueFrom:
#         configMapKeyRef:
#           name: course-config
#           key: duration
---
apiVersion: v1
kind: Pod
metadata: 
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapref:
        name: course-config

  
     
